"""deploy/prompt_secrets.py — interactive .env collection for fresh deploy.

Walks the operator through required secrets, masks input for sensitive values,
auto-generates random MCP_*_TOKEN, applies sane defaults for optional knobs,
and writes the result to .env with mode 0600.

Idempotent: if .env already exists and --force is not passed, prints the
existing key inventory and exits 0 (no overwrite).

Required system tool: `openssl` (for token generation).
"""
from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

import click

_REPO_ROOT = Path(__file__).resolve().parent.parent
_ENV_PATH = _REPO_ROOT / ".env"


def _gen_token() -> str:
    """Random URL-safe token (~43 chars), used for MCP_*_TOKEN defaults."""
    return secrets.token_hex(32)


@click.command()
@click.option("--force", is_flag=True, help="Overwrite existing .env (after confirm)")
def main(force: bool) -> None:
    if _ENV_PATH.exists() and not force:
        click.echo(f"\033[33m[prompt_secrets]\033[0m .env already exists at {_ENV_PATH}")
        click.echo("                 Re-run with --force to overwrite (will prompt confirm)")
        sys.exit(0)
    if _ENV_PATH.exists() and force:
        if not click.confirm(f"Overwrite {_ENV_PATH}?", default=False):
            click.echo("Aborted.")
            sys.exit(1)

    click.secho("\n=== AI Agent Studio — interactive .env setup ===\n", fg="cyan", bold=True)
    click.echo("Required secrets — paste values when prompted (input hidden for sensitive ones).\n")

    # ── Required secrets ────────────────────────────────────────────────────
    anthropic_key = click.prompt(
        "ANTHROPIC_API_KEY (Claude API key from https://console.anthropic.com)",
        hide_input=True,
    )
    tidb_password = click.prompt(
        "TIDB_PASSWORD (root password for the local TiDB; leave empty for default unauthenticated)",
        hide_input=True,
        default="",
        show_default=False,
    )
    line_token = click.prompt(
        "LINE_CHANNEL_ACCESS_TOKEN (from LINE Developers Console -> Messaging API channel)",
        hide_input=True,
    )
    line_user = click.prompt(
        "LINE_USER_ID (your LINE userId; starts with 'U', 33 chars)",
    )
    line_secret = click.prompt(
        "LINE_WEBHOOK_SECRET (LINE channel secret for HMAC; required)",
        hide_input=True,
    )

    # ── Optional Telegram fallback ──────────────────────────────────────────
    click.echo()
    if click.confirm("Configure Telegram fallback for alerts? (otherwise LINE-only)", default=False):
        tg_token = click.prompt("TELEGRAM_BOT_TOKEN", hide_input=True)
        tg_chat = click.prompt("TELEGRAM_CHAT_ID")
    else:
        tg_token, tg_chat = "", ""

    # ── Auto-generated tokens ───────────────────────────────────────────────
    mcp_write = _gen_token()
    mcp_notify = _gen_token()
    click.secho("\n[prompt_secrets] generated random MCP_WRITE_TOKEN + MCP_NOTIFY_TOKEN\n", fg="green")

    # ── Default-valued config ───────────────────────────────────────────────
    lines = [
        "# AI Agent Studio environment — generated by deploy/prompt_secrets.py",
        "# Do NOT commit this file; mode is 0600.",
        "",
        "# ── Anthropic ─────────────────────────────────────────────────────────",
        f"ANTHROPIC_API_KEY={anthropic_key}",
        "",
        "# ── TiDB (local docker compose; host-bound to 127.0.0.1) ─────────────",
        "TIDB_HOST=127.0.0.1",
        "TIDB_PORT=4000",
        "TIDB_USER=root",
        f"TIDB_PASSWORD={tidb_password}",
        "TIDB_DB=agent_memory",
        "",
        "# ── LINE Messaging API ───────────────────────────────────────────────",
        f"LINE_CHANNEL_ACCESS_TOKEN={line_token}",
        f"LINE_USER_ID={line_user}",
        f"LINE_WEBHOOK_SECRET={line_secret}",
        "",
        "# ── Telegram (optional fallback) ─────────────────────────────────────",
        f"TELEGRAM_BOT_TOKEN={tg_token}",
        f"TELEGRAM_CHAT_ID={tg_chat}",
        "",
        "# ── MCP authentication tokens (auto-generated) ───────────────────────",
        f"MCP_WRITE_TOKEN={mcp_write}",
        f"MCP_NOTIFY_TOKEN={mcp_notify}",
        "",
        "# ── Phase 1 / Phase 2 / Phase 3 feature flags ────────────────────────",
        "SHADOW_AGENTS=tech_analyst,portfolio_manager,sentiment_curator",
        "OPTIMIZER_ENABLED=0",
        "OPTIMIZER_AGENTS=tech_analyst,portfolio_manager,sentiment_curator",
        "OPTIMIZER_COST_CAP_USD=0.30",
        "SECTION2_ENABLED=true",
        "",
        "# ── Logging ──────────────────────────────────────────────────────────",
        "LOG_LEVEL=INFO",
        "",
        "# ── Snapshot integrity HMAC (optional, leave blank to disable) ───────",
        "SNAPSHOT_HMAC_KEY=",
    ]
    _ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(_ENV_PATH, 0o600)

    click.secho(f"\n[prompt_secrets] wrote {_ENV_PATH} (mode 0600)", fg="green", bold=True)
    click.echo("\nNext step: `make db-up` to start TiDB, then `make db-init seed snapshot` "
               "(or just `make install` from the top).")


if __name__ == "__main__":
    main()
